# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift-UIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'IQKeyboardManagerSwift'
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'HCSStarRatingView', '~> 1.5'
  pod 'ObjectMapper', '~> 3.4'
end
